#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Snake.Droid.Resource", IsApplication=true)]

namespace Snake.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int apple = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int apple1_50_50 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int apple2_50_50 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int apple3_50_50 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int dot = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int down_snake_head1_50_50 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int down_snake_tail_50_50 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int field_768_442 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int left_snake_head1_50_50 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int left_snake_tail_50_50 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int right_snake_head1_50_50 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int right_snake_head2_50_50 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int right_snake_head3_50_50 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int right_snake_head4_50_50 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int right_snake_tail_50_50 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int snake_body_50_50 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int up_snake_head1_50_50 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int up_snake_tail_50_50 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int waterrmelon_50_50 = 2130837523;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000b
			public const int lbtnDown = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int lbtnLeft = 2131099658;
			
			// aapt resource value: 0x7f060003
			public const int lbtnPause = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int lbtnPlay = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int lbtnStartGame = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int lbtnUp = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int lytField = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int lytFieldContainer = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int lytRoot = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int lytTopBar = 2131099649;
			
			// aapt resource value: 0x7f06000e
			public const int rbtnDown = 2131099662;
			
			// aapt resource value: 0x7f060004
			public const int rbtnRestart = 2131099652;
			
			// aapt resource value: 0x7f06000d
			public const int rbtnRight = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int rbtnUp = 2131099660;
			
			// aapt resource value: 0x7f060005
			public const int tvScore = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int MainMenu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
